name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install helpers
      run: sudo apt-get install tree
    - name: Test fpm action
      uses: bpicode/github-action-fpm@master
      with:
        fpm-args: '--debug -n mypackage -t deb -s dir ./build'
    - name: Tree
      run: tree
  
