name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: fpm
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: './build'
        fpm_opts: '--debug -n example -t deb -s dir --description "my app! lul"'
    - name: upoad bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: example_1.0_amd64.deb
        api_user: ${{ secrets.BINTRAY_API_USER }}
        api_key: ${{ secrets.BINTRAY_API_KEY }}
        gpg_passphrase: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
        repository: test_deb
        package: example
        version: '1.0'
        upload_path: pool/main/m
        publish: '1'
        calculate_metadata: 'true'
        deb_distribution: wheezy,jessie,stretch,buster,sid
        deb_component: main
        deb_architecture: amd64

